// Generates supabase/seed.sql from the same buildUmbrellas/buildArticles/buildPriceLists
// functions the in-memory store used to seed itself with, so the real database starts with
// the identical beach layout and price catalog instead of a hand-transcribed copy that could
// drift from src/data/seed.ts over time.
//
// Deliberately does NOT seed customers/bookings/conti/daily_stats -- those were demo/fake
// data for the mock store; a real deployment should start with an empty CRM and booking
// history, not fabricated customers.
//
// Run with: npx ts-node --compiler-options '{"module":"commonjs","esModuleInterop":true}' scripts/generate-seed-sql.ts

import { buildUmbrellas, buildArticles, buildPriceLists } from '../src/data/seed';
import * as fs from 'fs';
import * as path from 'path';

function sqlString(v: string | undefined | null): string {
  if (v === undefined || v === null) return 'null';
  return `'${v.replace(/'/g, "''")}'`;
}

function sqlBool(v: boolean): string {
  return v ? 'true' : 'false';
}

function sqlJson(v: unknown): string {
  return `'${JSON.stringify(v).replace(/'/g, "''")}'`;
}

const lines: string[] = [];
lines.push('-- Auto-generated by scripts/generate-seed-sql.ts -- do not hand-edit, regenerate instead.');
lines.push('');

const umbrellas = buildUmbrellas();
lines.push('insert into umbrellas (id, number, side, row, col, zone, has_cabin, status, current_booking_id, assigned_customer_id) values');
lines.push(
  umbrellas
    .map(
      (u, i) =>
        `  (${sqlString(u.id)}, ${u.number}, ${sqlString(u.side)}, ${u.row}, ${u.col}, ${sqlString(u.zone)}, ${sqlBool(
          u.hasCabin
        )}, ${sqlString(u.status)}, null, null)${i === umbrellas.length - 1 ? ';' : ','}`
    )
    .join('\n')
);
lines.push('');

const articles = buildArticles();
lines.push('insert into articles (id, name, category, base_price, unit) values');
lines.push(
  articles
    .map(
      (a, i) =>
        `  (${sqlString(a.id)}, ${sqlString(a.name)}, ${sqlString(a.category)}, ${a.basePrice}, ${sqlString(a.unit)})${
          i === articles.length - 1 ? ';' : ','
        }`
    )
    .join('\n')
);
lines.push('');

const priceLists = buildPriceLists();
lines.push('insert into price_lists (id, name, season, prices, active_from, active_to) values');
lines.push(
  priceLists
    .map(
      (p, i) =>
        `  (${sqlString(p.id)}, ${sqlString(p.name)}, ${sqlString(p.season)}, ${sqlJson(p.prices)}, ${sqlString(
          p.activeFrom
        )}, ${sqlString(p.activeTo)})${i === priceLists.length - 1 ? ';' : ','}`
    )
    .join('\n')
);
lines.push('');

const outPath = path.join(__dirname, '..', 'supabase', 'seed.sql');
fs.writeFileSync(outPath, lines.join('\n'));
console.log(`wrote ${outPath}`);
